POST http://localhost:3000/api/direct-debits/validate-clabe
Content-Type: application/json

{
  "clabe" : "638180000168328657"
}

###
POST http://localhost:3000/api/direct-debits/toku-webhook
Content-Type: application/json

{
    "id": "wheve_pQC-XSOMftTt2paMrBjJFvmnCPHwclDO",
    "event_type": "bank_account_verification.result",
    "bank_account_verification": {
        "id_bank_account_verification": "bav_ZQ80rZFu7gH6l0nAXntOHWms10cSYdCh",
        "status": "DONE",
        "validation": "SUCCESS",
        "reason": null,
        "voucher_url": {
            "pdf": "https://api-storage.trytoku.com/v1/streaming/xC6X3ikkYNPf7-EPzFMJT_kkZQNFfubOHhAi5nz4F7gx_t4JTGVoflQrtAlkdu_pIkHo3H7XpYj-TIiblBFUrvlvN0LDLfjMfIVbXRqc8pEzaTWMnaUU4Ismm6QPielhUqHtoaCS5sOxTcJuDP2vJV4Jr0U_2YU47B1QPpEw6TzIcB17iwn73qtBE5ZL2uqrPViXlW9_orPbg3P9YMC_juAblqUBfDC3cImMbjJgfIrnjdwEdN7qvxcNR6PvOJa7z48ufzGhSi0l6JyDFV81nnfVfB8P5dyyApiPmqKGB7D0VTWfv4pW9aWdJJFssvLuc9S3BHlMl0ufK-QblonP3NJWYcrEhJbRQeGn8NPLrB_Pq1ymKXC7VjmlkjZsCMMQVa31GvIC38658LNNV-Y_nGI1cnTywOUIZyReh4z_94m2CJ47sai2ZpEz2YtboBT0atcldjvMR_smC-baQFKY9KvbHV5FtPtUDWHC1k0cAamWtI8dqhJxMwStZy5ExyShmmCWHechc5tvOOeqYvG5YXebPIcpl_VWUXU-b0Zz--IF3X69YkPrhy3LFFoEjSxxOfQH8pxOTd8Si7QvqAONaG_fvjMMxAj7swI3VDvRdEpAhTXVVzdwL9Gir_Rg6IWAi4UMdoWsP7DrXg3DGgsL-POeIERm2lwmv2uBg1a9yfyJpD36_WM-NTEvxonjBXK8XSuyLrnPrZcYwPw3",
            "xml": "https://api-storage.trytoku.com/v1/streaming/0jpInxa78MPxe9MYsQwHVVRyckB-eZH6-qex0Gb7sBajeTMPfLllZRFU2fpbrOsTqy7WDHzklz4Kqj2utro37xi183YiOieG_9sAGtS-97qnwewH6yetPrvN4t9EUj1tNb4xAo8qRgaMojt8dpzuHC17AJdTG9QP14HXdx1Llzw_gb0YbKXYdiOVnYGTA8lZ1wwfHBt68u---aAlQ_OPQvCVdZmIUuZYH6R9LQjex0IMGq_5xEGateKigkqg7tb6dgwjBntJ1uW3FTDzPmrLQWWd6m_8sg17bkyNyHWG4E1boe510fcZOlvgAp7isfoMEb2NX0IjlFyjrbEuVddtc4AQmtnMKbiomp5R7IviHLgyjYPn2V0kNBIvkMC-XiB-D4QwrlyeVYyEqOinMB2YV1c83Wkp89gdVr2OaB6855h6XuUDkcU3OtEW9DTVLngKROv_47ZvBhYxX0M8k-qOLcUBiRV-8H0-0jOHrxTMAMthDUOKTTAYQK7iUkxuKXIF0dRflut8kropfMR_h_61UBFbXM-jNV5ow2M63f94zoGDnno5eC4ajzh1I5-HgADorfF4bEiIHEyEyMBcxhvq4TQX_IkA10NIt5OTPD4k-1nEB_LP-jBCYALiqaljay3m5IgqoP463GJA3tnBf9PCK_xvXODLzecx1nNKu0CkURp2LiIPr29Fw5HV9SEkm28E4y1_qP4vNtl10dYu"
        },
        "account_number": "012840015093214334",
        "customer_identifier": "TOMB971024UW4",
        "voucher_information": {
            "account_number": "012840015093214334",
            "customer_identifier": "TOMB971024UW4",
            "receiver_institution": "BBVA BANCOMER",
            "receiver_name": "BERNARDO TORRES MEDINA",
            "receiver_account_type": "40",
            "operation_date": "2025-07-10",
            "operation_time": "17:22:00",
            "spei_id": "40012",
            "signature": "PXDa8jXu+0JQN7DBl+Lv0R/8k7lnNftxx9qFCCsUDbKNzeWiPJmZ7WAj4AesQ598BRTLc1unm3N+IGzk4aUIhWDGutNm/MuBH3YV1rXy7Y8qci1p9kqNfOHMZu7xNliSBi8wu+UybSJnl9fZ/3AbdUvZLcE62ZlwG5ULftpitYziSi/XNjR/sZZ55NnibFMKiz0Vp0hn2NUFCLYQUpJZxEWIKFNxk24sALsXLEPY699In+g0W77eef/+dehfpRQtClXI7G09VmZoT/HKBVZYExO0NbPs/nWUFlYB9gDMIPr2KuEHQFH3sKbM7T6FYTo7fCv4+u+C5VgsMd2wQCmwAQ==",
            "certificate_number": "00001000000511796968",
            "cda_chain": "||01|10072025|10072025|172200|40012|STP|TRYTOKU S DE RL DE CV|40|646180328500700002|TRY220304U60|BBVA BANCOMER|BERNARDO TORRES MEDINA|40|012840015093214334|TOMB971024UW4|Validation transfer|000000000000000.00|000000000000000.01|NA|NA|0|0|NA|0|000000000000000.00|00001000000511796968||PXDa8jXu+0JQN7DBl+Lv0R/8k7lnNftxx9qFCCsUDbKNzeWiPJmZ7WAj4AesQ598BRTLc1unm3N+IGzk4aUIhWDGutNm/MuBH3YV1rXy7Y8qci1p9kqNfOHMZu7xNliSBi8wu+UybSJnl9fZ/3AbdUvZLcE62ZlwG5ULftpitYziSi/XNjR/sZZ55NnibFMKiz0Vp0hn2NUFCLYQUpJZxEWIKFNxk24sALsXLEPY699In+g0W77eef/+dehfpRQtClXI7G09VmZoT/HKBVZYExO0NbPs/nWUFlYB9gDMIPr2KuEHQFH3sKbM7T6FYTo7fCv4+u+C5VgsMd2wQCmwAQ==",
            "tracking_id": "2025071090646VCC2321551BPAUG"
        }
    }
}



###
POST http://localhost:3000/api/direct-debits
Content-Type: application/json

{
  "nombre1": "Bernardo",
  "nombre2": "Luis",
  "apellidoPaterno": "Torres",
  "rfc": "TOMB940505ABC",
  "curp": "TOMB940505HDFLRN07",
  "idNacionalidad": 1,
  "idEstadoCivil": 2,
  "dependientes": 0,
  "sexo": "M",
  "clabe": "012345678901234567",
  "urlFirma": "https://tuservidor.com/firmas/bertorres.png",
  "idSolicitudDomiciliacion": 123
}

###
GET http://localhost:3000/api/direct-debits/document/722110