POST http://localhost:3000/api/direct-debits/validate-clabe
Content-Type: application/json

{
  "clabe" : "638180000168328657"
}

###
POST http://localhost:3000/api/direct-debits/toku-webhook
Content-Type: application/json

{
    "id": "wheve_Y2ObUsOSYM0of3hE9kgzllgYH_l4OIey",
    "event_type": "bank_account_verification.result",
    "bank_account_verification": {
        "id_bank_account_verification": "bav_INHfcNWaZCZKyTLMQ2st35NhjR2xFPwN",
        "status": "DONE",
        "validation": "SUCCESS",
        "reason": null,
        "voucher_url": {
            "pdf": "https://api-storage.trytoku.com/v1/streaming/kd-nJmmrbHZME_dBhCT7sihdnHj0uO0_UKqhQ6jkha6aYFUMmzmdBgGZ5ETXRFnlpSE6LofmAc87ZEoj0wA6v_CFomEMEQ8Bi7wyrl05q7QsWAu5-v7ajBLEKOZ3Jdu3UCtnizY5e5Wc43aHmPHCHv2lGLlVrTOt0hyg-7k9i5Dobq_wZhjHEJ4mXTNHWFW7m-WioAhp5jHj-d2rUj0ZiRkeYSsSvmj6kK3wK6Es7dgAL7Q7Al3SQaX_bE4pWZmPuVVdtfjDMb5JXA2qCEhf5o1m9XJMHyenbC8x7OjjSkTRoQWTnKbZPmR8HerhtOd4CExvRda7ySaNP5_3go96Fuh2caR69X84deykDBkz1NB9NtsEkE4lggaKuVA6fkckH5ycoh9y2lxBGxkmk5uZJH74oHkFmHjNHswoWA7dPz0fZ4DM779vibA9RNTyMr-0EnFpUVetO75Z956Cbg_neS0ZXOwWSncLCCYHDd7IpW4SF-YtODpfoQGPtl2sHnPVob5R_LJOe3tAsD5o3nvBmmhM9DJjTQsIQ6AyEz0dy6WUNU-R8jTFArjK9NHsR8SxAHlQXc56CAcnaW64yIQB-tJFoJKXDIA46-hC6yeo1kDpG8Oe1OrC6SNy6ntW4xC9myZN8N25WZtuyEwMnDxAQuwXpMptbFA70e7xab08Z3FdDkR3vHtg2PgdvIlOn24JKZyaXyVS5ILk-FTB",
            "xml": "https://api-storage.trytoku.com/v1/streaming/PW9HR_01nqFslhlhLvW1EuwoXFdwoIxFGkjEGLkSz1loK_37jTSfjHAUWoOpCnmbkBQrtQ7R2-Pna6yJZKkD4Q_Jsd5pO-KdOCVv2UqvK2xx6LK6VWVmiezzw8lJm4oMaRntOLDpCZ7e0esfOkdhHdQ419uFQej19pcH4S-hQ8m2m6nZx093W5bSaPPXYsZ2EcJflqHvS6ZjodK9Z1pMmx37CTJ5zZjIjLx6_DQ9RiPskDkd37TZW54BD0ko3_OsmTEmhuZ4oXH2V67pkchDGHkMXrWNgcrGgu0LqiDm3aQG2mZDmQa5MNBzkbQz7RXiLBQTR4vjdZovv1YLVXdmTKwZ1gIPSgXm1wifH3TieWEJNqy1bZPvOvjrr8k8URG_l2YLoGF3JG-V7z7fsAKp8JcufZtzoKoJPJjDdAomDkdy49qQ-ungdwXJvFEPDjAwGtW90Gbf9WlKQ-PeQA9l-GoC57b-7_LZbLRxgcYBF-rByz0bxDfyhFjFmnqgpOcqgJhoqqjxGXW3XhTbura17HoPCFduC1Kt-DkVWjvc9SVk0WIIcdva_2I74CP-wLNHJIz6TgbegOY_GCZm0exG3yohhkQfKlDHLRGwIU9e9E_fn3ST7B3zevNDGmDkIkZnFIVE0JwNfBgAN8Q2Acgw1UdcSAgvXoTAzyc2UyzdC4A6mwctXWR_wQXr-7yrgYVm-eC8S9cm8bvRsjNS"
        },
        "account_number": "012840015093214334",
        "customer_identifier": "TOMB971024UW4",
        "voucher_information": {
            "account_number": "012840015093214334",
            "customer_identifier": "TOMB971024UW4",
            "receiver_institution": "BBVA BANCOMER",
            "receiver_name": "BERNARDO TORRES MEDINA",
            "receiver_account_type": "40",
            "operation_date": "2025-07-08",
            "operation_time": "13:18:20",
            "spei_id": "40012",
            "signature": "R6jpPszBvLc3lVhx1OoA1bYbnPdjWdnGLzY9I9gF7IVURMzXEtx20Gy//TI8eo+QXxqYHHOMjJQrStzak5G2VjIeQX8jAFYFawkfJYDDlhYGrfYt6A5cxSiIoN9JQvqeu/CxGBnNiCMlo8YmbyVB37hebQ1uFBjaFCx+W/d7hgI10AKskuOVa+XTowOiN5ky6zF0PL6D8eGgrY2P3q/ZySfIwBtwY3X3l8cI+Huzh3PV0EpwTCEsCGAhTy+VbjaBCIk5KkA6blCh5rAhfwMcND8q5JGA1A4S9J7vytm/EtEuUTu4vtkL9ra1b6/rWdBgqahdma2o8XJEcnTATRjuuA==",
            "certificate_number": "00001000000511796968",
            "cda_chain": "||01|08072025|08072025|131820|40012|STP|TRYTOKU S DE RL DE CV|40|646180328500700002|TRY220304U60|BBVA BANCOMER|BERNARDO TORRES MEDINA|40|012840015093214334|TOMB971024UW4|Validation transfer|000000000000000.00|000000000000000.01|NA|NA|0|0|NA|0|000000000000000.00|00001000000511796968||R6jpPszBvLc3lVhx1OoA1bYbnPdjWdnGLzY9I9gF7IVURMzXEtx20Gy//TI8eo+QXxqYHHOMjJQrStzak5G2VjIeQX8jAFYFawkfJYDDlhYGrfYt6A5cxSiIoN9JQvqeu/CxGBnNiCMlo8YmbyVB37hebQ1uFBjaFCx+W/d7hgI10AKskuOVa+XTowOiN5ky6zF0PL6D8eGgrY2P3q/ZySfIwBtwY3X3l8cI+Huzh3PV0EpwTCEsCGAhTy+VbjaBCIk5KkA6blCh5rAhfwMcND8q5JGA1A4S9J7vytm/EtEuUTu4vtkL9ra1b6/rWdBgqahdma2o8XJEcnTATRjuuA==",
            "tracking_id": "2025070890646VCC1918079UECJK"
        }
    }
}

###
POST http://localhost:3000/api/direct-debits
Content-Type: application/json

{
  "nombre1": "Bernardo",
  "nombre2": "Luis",
  "apellidoPaterno": "Torres",
  "rfc": "TOMB940505ABC",
  "curp": "TOMB940505HDFLRN07",
  "idNacionalidad": 1,
  "idEstadoCivil": 2,
  "dependientes": 0,
  "sexo": "M",
  "clabe": "012345678901234567",
  "urlFirma": "https://tuservidor.com/firmas/bertorres.png",
  "idSolicitudDomiciliacion": 123
}

###
GET http://localhost:3000/api/direct-debits/document/722110