POST http://localhost:3000/api/individuals/validate
Content-Type: application/json

{
  "folioOrden": "CDI721953VDW",
  "codigo": 1505,
  "idEstadoNacimiento": 9,
  "fechaNacimiento": "1997-10-24"
}

###
GET http://localhost:3000/api/individuals/CDI721953VDW

###
GET http://localhost:3000/api/individuals/bank/CDI721953VDW

### 
POST http://localhost:3000/api/individuals/send-sms/CDI700046VDW